name: Deploy Documentation

on:
  push:
    branches: [ main ] # Trigger whenever you push code updates

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx pydata-sphinx-theme gosling
          pip install -e . # Installs hub2gos in editable development mode

      - name: Compile HTML Site
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Publish to GitHub Pages Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html